services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buy-it-frontend
    ports:
      - "8000:80"  # map container's port 80 to host's port 
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    restart: unless-stopped