apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-it-frontend
  labels:
    app: buy-it
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buy-it
  template:
    metadata:
      labels:
        app: buy-it
    spec:
      containers:
        - name: frontend
          image: farhanmullick/buy-it-frontend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: buy-it-service
spec:
  type: NodePort
  selector:
    app: buy-it
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # This will be accessible via localhost:30090 on Docker Desktop