name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: your-dockerhub-username/your-frontend-image-name

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: 🔧 Build, Lint, Test

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: ✅ Lint Code
        run: npm run lint

      - name: 🧪 Run Unit & Integration Tests
        run: npm run test:unit

      - name: 🛠️ Build Project
        run: npm run build

  docker:
    name: 📦 Docker Build and Push
    runs-on: ubuntu-latest
    needs: build-and-test  # Waits for build-and-test job to succeed

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔨 Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: 📤 Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest
